    version: "3.7"
    services:
        jenkins:
            image: jenkins/jenkins:latest
            ports:
                -   8090:8080
        sonarqube:
            image: sonarqube:latest
            ports:
                -   9000:9000
        registry:
            image: registry:latest
            ports:
                -   5000:5000       